name: Deploy to S3 + Invalidate CloudFront

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET }}
  CF_DISTRIBUTION_ID: ${{ vars.CF_DISTRIBUTION_ID }}
  ROLE_ARN: ${{ vars.ROLE_ARN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS CLI v2
        uses: unfor19/install-aws-cli-action@v1

      - name: Who am I? (sanity check)
        run: aws sts get-caller-identity

      # Upload HTML with no-cache so changes show immediately
      - name: Upload HTML (no-cache)
        run: |
          aws s3 sync . s3://$S3_BUCKET \
            --exclude "*" --include "*.html" \
            --exclude ".git/*" --exclude ".github/*" \
            --cache-control "no-cache, no-store, must-revalidate" \
            --delete

      # Upload other assets with long cache (use hashed filenames if possible)
      - name: Upload assets (long cache)
        run: |
          aws s3 sync . s3://$S3_BUCKET \
            --exclude "*.html" \
            --exclude ".git/*" --exclude ".github/*" \
            --cache-control "public, max-age=31536000, immutable"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$CF_DISTRIBUTION_ID" \
            --paths "/*"
